# Config file for automatic testing at travis-ci.org
# This file will be regenerated if you run travis_pypi_setup.py

language: python
python: 3.5
sudo: false

env:
  - TOXENV=py35
  - TOXENV=py34
  - TOXENV=py27
  - TOXENV=pypy

before_install:
  - python --version
  - uname -a
  - lsb_release -a

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: 
  - pip install -U tox twine
  - virtualenv --version
  - easy_install --version
  - pip --version
  - tox --version

script:
  - tox -v

after_failure:
  - more .tox/log/* | cat
  - more .tox/*/log/* | cat

before_cache:
  - rm -fr $HOME/.cache/pip/log

cache:
  diretories:
    - $HOME/.cache/pip

notifications:
  email:
    on_sucess: never
    on_failure: always

# command to run tests, e.g. python setup.py test
# After you create the Github repo and add it to Travis, run the
# travis_pypi_setup.py script to finish PyPI deployment setup
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: rolando
  password:
    secure: vZ/53JIl1uaqLjoqU4Bi/F9xV/KJPjx8r6lI7R9/TbGVxxJiCYd7OAvU2+MAvPqckIbGK3F7h+heVBWscVsJwvQ3PeUq2oBslgG45kgrbGtFCXlvjfl2oF6VtYewubi/kelqSqczqbRwLcyKBSQMas9tAQOIL8WNxXo/aZeViVOzhtoB/H1QASmNxTxfxwbtLUNUemMEW72bF6TgcAEKedQ/7g9NTD8DCNXjJe0I4mhorje45ie4OsoWxXYOaPwGecWLPOP9VOmiFixgmBZagmVIagBVvvqoxzMjjWMT8RMjXz71rPUIWa2IVZcIdXAmLQ3FFzP6ZovUusVxFE997beIH6atBiJEpmpMYKxfcEjLf8u0m5V8eApoJeZPeyb2liP+iq3i/rcv3njlpcymQUs7e5uBpItskhORaGivDdU+pIlcl5Mtr+EycxUkXxHsZFnRh0O1LOq6MFTJT9nbwvBwUaKO1U0xBVvqa3QsPhSv8hEZK0z04wBCJYPbkFR8vxwhklIFY7/XpnILF7uJAF4v7BrVNDy3reooaRvTqUKYJzx1gNoK0EG+1U8boPnJrGKMa3ylfzUKoO/6PnD/gsdcmfDHjFSsCCrb3yvbx+4wclIJyEVTRFMFPbpclfZu9ybYKDJ1InqPqDAlbB00AJDDDpfm1VfAABDtd65UjO8=
  on:
    tags: true
    repo: rolando/binary-repr
    condition: $TOXENV == py27
